### ISSUE TITLE
Error: only one instance of babel/polyfill is allowed

### ISSUE THREAD

**Issue by inromualdo** [Urigo/meteor-static-templates#13]
This error appear when i install it

**Comment by adrianolsk** [comment]
@inromualdo  are you using ng-include for something? The only problem I had with this package is when I was trying to include the header and footer html with ng-include. But I change my app and created  components for header and footer.

**Comment by Urigo** [comment]
@inromualdo please add more information, a reproduction.
To little information for me to solve this

**Comment by spalonytoster** [comment]
@Urigo I came across the same error message. I learned that the source of evil in this case is (as @adrianolsk pointed out) `ng-include` directive. Reproduction:

1. Run `meteor-angular-socially-step1`.
2. Change from `angular-templates` to `urigo:static-templates`.
3. Crash.

In my case using component as a template is not a good solution since I need to use the same controller.

Thanks for looking into that case,
Maciej
