### ISSUE TITLE
Package Conflicting with angular-compilers

### ISSUE THREAD

**Issue by klynicol** [Urigo/meteor-static-templates#18]
When trying to run meteor, I got the following error:

> While determining active plugins:
error: conflict: two packages included in the app (urigo:static-templates and angular-compilers) are both trying to handle *.html

Not sure how to solve this issue.

**Comment by SimonSimCity** [comment]
... which is because meteor doesn't allow you having two compilers trying to handle the same file extension.

Are you still facing this problem?

I guess you're transiting over from `AngularJS` to `Angular` and want to do it slowly, right?

If this is the case - since you in the end anyways won't use this plugin but use `angular-compiler` which is made for `Angular` - you should remove it and e.g. use `templateUrl` instead of `template` in your controllers (don't know what other places I'd use it ...). I've tried installing `angular-compiler` on an `AngularJS` app and can confirm that it doesn't work without installing the npm packages for `Angular` and stopped testing from there on.

I would take it up in the list of known issues, since it is an issue that doesn't really have a solution that could be taken within the boundaries of this package.

**Comment by klynicol** [comment]
Thanks @SimonSimCity, I've been working on getting up to date with my angular-meteor project. I do not face this problem anymore, closing.
